[package]
name = "welcomer"
version = "0.1.1"
edition = "2021"
description = "This is a simple CLI program to say hello in different languages."
license = "MIT"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
